### ISSUE TITLE
Enable external Postgres and Redis hosting (URL Override) on docker image

### ISSUE THREAD

**Issue by ricxsar** [SFDO-Tooling/MetaDeploy#1087]
We would like to host MetaDeploy to AWS instead of Heroku however I can't find any documentation on how to override the Postgres and Redis URL.

We're able to replicate the docker hosting (Heroku) on AWS ECS but it still referencing local Postgres and Redis which results in an error.

We are hosting Postgres on AWS RDS and Redis on AWS ElastiCache. Hoping you will take action on the request.

Thanks!

**Comment by davisagli** [comment]
The comments I made on https://github.com/SFDO-Tooling/MetaCI/issues/1007 also apply to MetaDeploy.

**Comment by ricxsar** [comment]
Great! Thanks. I will close this issue and continue discussing things over there.
