### ISSUE TITLE
Issues on deploying MetaDeploy on Heroku

### ISSUE THREAD

**Issue by ricxsar** [SFDO-Tooling/MetaDeploy#1088]
I would like to spin up Metadeploy on Heroku but it can't due to the limit on how many free dynos can be spawn.
![image](https://user-images.githubusercontent.com/8968902/76827426-bb2eb580-6859-11ea-9ea8-8d86540be791.png)
![image](https://user-images.githubusercontent.com/8968902/76827512-efa27180-6859-11ea-8d2c-e672033f5d42.png)

**Comment by ricxsar** [comment]
I was able to deploy on Heroku editing this line on `app.json` to 
```
"formation": {
    "web": {
      "quantity": 1
    },
    "scheduler": {
      "quantity": 0
    },
    "devworker": {
      "quantity": 1
    }
  },
```

**Comment by davidmreed** [comment]
@ricxsar I will ask that we clarify the Heroku requirements for this application. I don't believe we can commit to supporting deployment in free-tier Heroku accounts.

For development and experimentation, you may also be interested in the work a member of our team did recently to support working with MetaDeploy in [Docker](https://github.com/SFDO-Tooling/MetaDeploy/blob/master/docs/running_docker.rst).

**Comment by davidmreed** [comment]
We're tracking a request to document our Heroku requirements as W-7341597. I'll close out this issue for now. Thank you!

**Comment by ricxsar** [comment]
@davidmreed Thank you.
