### ISSUE TITLE
Error on NPSP Installer when attempting to install into Profession Edition Org not clear

### ISSUE THREAD

**Issue by mbeaty-sf** [SFDO-Tooling/MetaDeploy#1149]
When trying to install into a Professional Edition org: Server Error (500) is displayed. The error message doesn't describe the actual issue, and leads users to think clearing their cache is the solution, but the same issue is encountered

**Steps to Reproduce**
1. Setup a Professional Edition Org
2. Navigate to https://install.salesforce.org/products/npsp/3.172 and attempt to install NPSP into the org

**Workaround**
Ensure that NPSP Installer is being pointed towards an Enterprise or Unlimited edition org, based on the steps outlined here https://powerofus.force.com/s/article/NPSP-Install

**Comment by davisagli** [comment]
This was fixed in #1172
