### ISSUE TITLE
Internal translations.json issue

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/MetaDeploy#272]
This is a minor issue, but I was researching how you use translations.json so I could copy it, and I noticed something a bit weird.

It makes two calls to the server, just as my MetaCI copy of the code does:

https://metadeploy.herokuapp.com/static/en-US/translation.json

https://metadeploy.herokuapp.com/static/en/translation.json

But the first one returns an HTML home page for the Django app instead of real JSON. So arguably, there are a couple of minor issues to be fixed:

1. The server is swallowing 404s and turning them into 200s. I guess that it expects the client to look at the URL a second time and decide what to do. Arguably, it should only defer a particular subset of the URL space to the client, to make debugging a bit easier. (that's an HTTP purist position)

2. The client is swallowing the fact that the response it got could not be parsed as JSON. Arguably it should at least output a console warning. But perhaps it doesn't care because it will get the correct data later from the other URL. (that's a log-all-issues purist position)

3. Is there a way to configure the library to just look for one file? It seems like only in the distant future would we have two-level language locales. It seems a waste of an HTTP call...(also very minor of course).

I'll leave it to you to decide if you agree these are issues and if you think they are worth fixing.

**Comment by jgerigmeyer** [comment]
@prescod Good catches.

1. I agree this is an issue, worth fixing IMO. In local dev I get a `404`, but on staging I get a `200`.

2. Again you're correct, and I will fix this.

3. Hm, I'm not sure there's a great way. We're using https://github.com/i18next/i18next-browser-languageDetector, and it detects `en-US` and then we fallback to `en`. I think a decent solution would be to just change the file in the repo (and the fallback) to `en-US`?

**Comment by prescod** [comment]
Maybe I was mislead but when I fiddled with this it seemed like it wasn't a fallback but more of a layering strategy? Like it would allow you to have a common file for English and then sub-files for Brits, Canucks and Yanks? So when I moved it back and forth from en-us to en it kept asking me for the other one. It was a couple of weeks ago so I might be mis-remembering, but I had the strong impression that it wanted two files.

My most recent checkin to MetaCI just gives it an empty file for en-US.

**Comment by wlonk** [comment]
I can work on some of the Django-server-response stuff here.

**Comment by jgerigmeyer** [comment]
> Maybe I was mislead but when I fiddled with this it seemed like it wasn't a fallback but more of a layering strategy? Like it would allow you to have a common file for English and then sub-files for Brits, Canucks and Yanks? So when I moved it back and forth from en-us to en it kept asking me for the other one. It was a couple of weeks ago so I might be mis-remembering, but I had the strong impression that it wanted two files.
> 
> My most recent checkin to MetaCI just gives it an empty file for en-US.

Ah, that makes sense. Is there a reason to use an empty file for `en-US` instead of just letting it hit a 404?

**Comment by wlonk** [comment]
(I've made it such that missing static files will 404 over in PR #274.)
