### ISSUE TITLE
Running make dev-install fails on pip-sync not found

### ISSUE THREAD

**Issue by joeythomaschaske** [SFDO-Tooling/MetaDeploy#3478]
I am trying to run MetaDeploy locally and I am following the steps in [running.md](https://github.com/SFDO-Tooling/MetaDeploy/blob/main/docs/running.md)

I am stuck on the step where it says to run `make dev-install`.

Output:
```bash
$: make dev-install         

pip-sync requirements/*.txt
/bin/sh: pip-sync: command not found
make: *** [dev-install] Error 127
```

A google search tells me pip-sync is a tool in pip-tools.

Does pip-tools need to be installed? And if so, how do you install it with `virtualenvwrapper`?

**Comment by TheBitShepherd** [comment]
If you have your virtualenv activated, you should be able to install with `pip install pip-tools`. We could consider adding this to the beginning of the `dev-install` target.

**Comment by joeythomaschaske** [comment]
> If you have your virtualenv activated, you should be able to install with `pip install pip-tools`. We could consider adding this to the beginning of the `dev-install` target.

Well that was easy. Should I close this task or leave it open? Not sure if a change needs to be made to the make file or docs based on this issue?

**Comment by TheBitShepherd** [comment]
I can go ahead and close this, glad this helped :)
