### ISSUE TITLE
Installation Errors with products that extend a public managed package (EDA)

### ISSUE THREAD

**Issue by FranciscoJOlmos** [SFDO-Tooling/MetaDeploy#3500]
I have a managed package that we built on top of EDA, and I added it to our instance of MetaDeploy.
I'm getting errors when testing the install.

https://aka-metadeploy.herokuapp.com/products/CourseCalendar/1.0/install/jobs/XkDYPzZ

 
![image](https://user-images.githubusercontent.com/37127920/221295688-692eed35-9886-4f0e-a624-45f35417a0e2.png)

I don't know if this helps, but we had a similar issue when we first started working with Metecho.

**Comment by davidmreed** [comment]
Hi @FranciscoJOlmos - I love that you're using MetaDeploy to ship EDA extensions!

Unfortunately, this is something that there's no real fix for, and it goes to how GitHub App permissioning works. GitHub requires that your GitHub App be installed in the EDA repo, even though EDA is actually open source. We cannot install your app in our repo, however

I have a general recommendation, though, that you should refrain from installing parent products in your own installer. The reason for that is that your customer may have customized, for example, the EDA unmanaged metadata. If you re-deliver that metadata, you'll overwrite their changes.

Instead, I recommend using a _preflight check_ to validate that EDA is installed, and _not_ include the `update_dependencies` task in your installer plan.
