### ISSUE TITLE
Can't create or modify users

### ISSUE THREAD

**Issue by carlosvl** [SFDO-Tooling/MetaDeploy#447]
When you go into an existing user the information showing in the fileds are for another one and will now allow you to commit changes
here is a video with the behavior
https://drive.google.com/open?id=1z87dLQ7T-UCah2s2vnZAVZrIxZ5jbxC_

**Comment by davisagli** [comment]
I can't reproduce this in our instance of MetaDeploy. I suspect your browser or a password manager is mistaking this for a login form and autofilling the username.

**Comment by carlosvl** [comment]
welp
you are correct
seems to be something caused by last pass
I had to run it on incognito mode with our the extension
